services:
  db:
    image: postgres:16-alpine
    container_name: employee-db
    environment:
      POSTGRES_DB: employee_service
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employee_service
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      SSN_HASH_SECRET: ${SSN_HASH_SECRET}
    ports:
      - "8081:8081"

volumes:
  pgdata: